server:
  port: 19092

spring:
  profiles:
    active: dev
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0